     - name: install jq and unzip
       apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
       loop: ['jq','unzip']

     - name: check latest terraform version
       shell: curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | egrep 'terraform_[0-9]\.[0-9]{1,2}\.[0-9]{1,2}_linux.*amd64' | sort -V | tail -1
       register: result
       args:
        warn: no

     - set_fact: url="{{ result.stdout }}"

     - name: download latest version
       get_url:
        url: "{{ url }}"
        dest: /sites/terraform.zip
        mode: '0755'

     - name: extract terraform zip file
       unarchive:
        src: /sites/terraform.zip
        dest: /usr/local/bin
        remote_src: yes

     - name: Check terraform version
       command: terraform --version
       register: result

     - debug: msg={{ result.stdout }}

     - name: Delete terraform zip file from /sites
       file:
        path: /sites/terraform.zip
        state: absent
