- name: configuring awscli using ansible
  hosts: localhost
  become_user: ubuntu
  vars_prompt:
    - name: aws_key_id
      prompt: "Enter your AWS terraform user Key ID form CSV File"
      private: no
    - name: aws_access_key
      prompt: "Enter your AWS terraform user Access Key form CSV File"
      private: no
    - name: aws_region
      prompt: "Enter your AWS region"
      private: no
    - name: aws_format_output
      prompt: "Enter output type(Optional)"
      private: no
  
  tasks:
    - name: install phython pip
      command: sudo apt install python3-pip -y
      args:
        warn: no

    - name: run installation
      command: pip3 install --upgrade --user awscli

    - name: install aws cli
      apt:
        name: awscli
        state: present
      become: yes

    - name: check aws version
      command: aws --version
      register: result
    - debug: msg="{{ result.stdout }}"

    - name: create aws directory if not present
      file:
        path: ~/.aws
        state: directory
    - name: create credentials file
      file:
        path: ~/.aws/credentials
        state: touch
        mode: '0600'
    - name: create config file
      file:
        path: ~/.aws/config
        state: touch
        mode: '0600'
    - name: add key values to credentials file
      copy:
        content: |
                 [default]
                 aws_access_key_id = {{ aws_key_id }}
                 aws_secret_access_key = {{ aws_access_key }}
        dest: ~/.aws/credentials

    - name: add region to config file
      copy:
        content: |
                 [default]
                 region = {{ aws_region }}
        dest: ~/.aws/config
