- name: Creating nexus repository
  hosts: nexus
  become: yes
  
  vars:
   data_dir: "/sites/nexus-data"

  tasks:
  
   - name: Set authorized key for user ubuntu copying it from current user
     authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

   - name: install docker 
     apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
     loop: ['python-apt', 'docker.io']

   - name: add docker to user
     command: sudo usermod -aG docker $USER
     become_user: ubuntu
     args:
       warn: no

   - name: download nexus image
     command: docker pull sonatype/nexus3

   - name: create nexus volume folder
     file:
      path: "{{ data_dir }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0777'

   - name: Run the docker image
     command: docker run -it -p 8081:8081 --name nexus -v "{{ data_dir }}":/nexus-data  -d sonatype/nexus3
