- name: Installing k8s on master node
  hosts: k8smaster
  become: yes
  
  tasks:
   - name: Set authorized key for user ubuntu copying it from current user
     authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

   - name: Add Docker's official GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: add stable docker repo
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: add k8s key value
     apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

   - name: add k8s stable repo
     apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      filename: /etc/apt/sources.list.d/kubernetes
      state: present

   - name: install docker kubectl kubelet and kubeadm
     apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
     loop: ['docker-ce=18.06.1~ce~3-0~ubuntu', 'kubelet=1.13.5-00', 'kubeadm=1.13.5-00', 'kubectl=1.13.5-00'] 
   
   - name: mark hold of kubeadm kubectl and kubelet update
     shell: apt-mark hold docker-ce kubelet kubeadm kubectl
     args:
      warn: no
 
   - name: add ubuntu user to docker group
     shell: usermod -aG docker $USER

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - name: Initialize the cluster on master node
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16
     register: result

   - debug: msg={{ result.stdout }}

   - name: Set up local kubeconfig
     file:
        path: $HOME/.kube
        state: directory
     become_user: ubuntu

   - name: copy k8s config files to kube folder
     shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
     become_user: ubuntu
     args:
      warn: no

   - name: Install weave network
     become: false
     shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
   - pause:
         seconds: 30

   - name: Check the nodes
     become: false
     shell: kubectl get nodes
     register: nodes

   - debug: msg={{ nodes.stdout }}
