   - name: Add Docker's official GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: add stable docker repo
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: add k8s key value
     apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

   - name: add k8s stable repo
     apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      filename: /etc/apt/sources.list.d/kubernetes
      state: present

   - name: install docker kubectl kubelet and kubeadm
     apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
     loop: ['docker-ce=18.06.1~ce~3-0~ubuntu', 'kubelet=1.13.5-00', 'kubeadm=1.13.5-00', 'kubectl=1.13.5-00'] 
  
   - name: mark hold of kubeadm kubectl and kubelet update
     shell: apt-mark hold docker-ce kubelet kubeadm kubectl
     args:
      warn: no

   - name: add ubuntu user to docker group
     shell: usermod -aG docker $USER

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - name: join master node
     shell: kubeadm join 172.31.6.81:6443 --token fkryx4.wv4esrf1q1tr7km0 --discovery-token-ca-cert-hash sha256:26441357fdd2e64ae3f59b0d39a662364f0322ce21546bb75ab1f5f5af1dbfbd
     args:
        warn: no
   - pause:
         seconds: 30
