- name: installing k8s and joining worker node with master
  hosts: k8sworker
  become: yes
  
  tasks:
   - name: Set authorized key for user ubuntu copying it from current user
     authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
   
   - include: install-k8s.yml
   - include: check-nodes.yml
