   - name: install docker kubectl kubelet and kubeadm
     apt:
      name: ['docker-ce=18.06.1~ce~3-0~ubuntu','kubelet=1.13.5-00','kubeadm=1.13.5-00','kubectl=1.13.5-00']
      state: present
      update_cache: yes
  
   - name: mark hold of kubectl kubeadm and kubelet
     shell: apt-mark hold docker-ce kubelet kubeadm kubectl

   - name: add ubuntu user to docker group
     shell: usermod -aG docker $USER

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - name: Initialize the cluster on master node
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16
     register: result

   - debug: msg={{ result.stdout }}

   - name: create a .kube folder
     file:
        path: $HOME/.kube
        state: directory
     become_user: ubuntu

   - name: copy k8s config files to kube folder
     shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
     become_user: ubuntu
     args:
      warn: no

   - name: Install weave network
     become: false
     shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
   - pause:
         seconds: 30

   - name: Check the nodes
     become: false
     shell: kubectl get nodes
     register: nodes

   - debug: msg={{ nodes.stdout }}
