- name: Creating nexus repo
  hosts: nexus
  become: yes

  tasks:
   - name: Set authorized key for user ubuntu copying it from current user
     authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
   - name: install docker 
     command: apt-get install docker.io -y
     args:
       warn: no
   - name: add docker to user
     command: sudo usermod -aG docker $USER
     become_user: ubuntu
     args:
       warn: no
   - name: download nexus image
     command: docker pull sonatype/nexus3
   - name: create nexus volume folder
     file:
      path: /sites/nexus-data
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0777'
   - name: Run the docker image
     command: docker run -it -p 8081:8081 --name nexus -v /sites/nexus-data:/nexus-data  -d sonatype/nexus3
